# Setup GitHub Pages
# This script creates gh-pages branch and deploys deployment files

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   Setup GitHub Pages Deployment" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Save current branch
$currentBranch = git branch --show-current
Write-Host "Current branch: $currentBranch" -ForegroundColor Yellow

# Check if gh-pages exists
$ghPagesExists = git branch -r | Select-String "origin/gh-pages"

if ($ghPagesExists) {
    Write-Host "gh-pages branch already exists. Checking out..." -ForegroundColor Yellow
    git checkout gh-pages
    git pull origin gh-pages
} else {
    Write-Host "Creating new gh-pages branch..." -ForegroundColor Yellow
    git checkout --orphan gh-pages
    git rm -rf . 2>$null
}

Write-Host ""
Write-Host "Copying deployment files..." -ForegroundColor Yellow

# Copy deployment files
$deploymentFiles = @(
    "Deployment\index.html",
    "Deployment\DemoDeploy.appinstaller",
    "Deployment\update.json",
    "Deployment\DemoDeploy_1.0.1.0_x64.msix"
)

foreach ($file in $deploymentFiles) {
    $fileName = Split-Path $file -Leaf
    if (Test-Path "..\$file") {
        Copy-Item "..\$file" -Destination ".\$fileName" -Force
        Write-Host "  ✅ Copied: $fileName" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️  Not found: $file" -ForegroundColor Yellow
    }
}

# Create README for gh-pages
@"
# DemoDeploy - Deployment Files

This branch contains deployment files for DemoDeploy app.

## 🌐 Live Site
Visit: https://luongsosad.github.io/Deploy-WinUI/

## 📦 Installation
Click the Install button on the website or use this URL:
``````
ms-appinstaller:?source=https://luongsosad.github.io/Deploy-WinUI/DemoDeploy.appinstaller
``````

## 📝 Files
- **index.html** - Landing page
- **DemoDeploy.appinstaller** - AppInstaller manifest
- **update.json** - Update manifest  
- **DemoDeploy_1.0.1.0_x64.msix** - MSIX package

---
*Auto-generated by Setup-GitHubPages.ps1*
"@ | Out-File -FilePath ".\README.md" -Encoding utf8

Write-Host "  ✅ Created: README.md" -ForegroundColor Green
Write-Host ""

# Commit and push
Write-Host "Committing files..." -ForegroundColor Yellow
git add .
git commit -m "Deploy: Update deployment files for v1.0.1"

Write-Host ""
Write-Host "Pushing to GitHub..." -ForegroundColor Yellow
git push -u origin gh-pages

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "✅ GitHub Pages setup complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Go to: https://github.com/Luongsosad/Deploy-WinUI/settings/pages" -ForegroundColor White
Write-Host "2. Set Source to: gh-pages branch" -ForegroundColor White
Write-Host "3. Wait 1-2 minutes for deployment" -ForegroundColor White
Write-Host "4. Visit: https://luongsosad.github.io/Deploy-WinUI/" -ForegroundColor White
Write-Host ""

# Return to original branch
Write-Host "Returning to $currentBranch branch..." -ForegroundColor Yellow
git checkout $currentBranch

Write-Host "Done! ✅" -ForegroundColor Green
